// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

typedef Eigen::MappedSparseMatrix<double> MSpMat;
typedef MSpMat::InnerIterator InIterMat;

// runGibbsCpp
List runGibbsCpp(IntegerVector incoming_component_assignments, MSpMat component_doc_matrix, MSpMat component_word_matrix, NumericVector component_sizes, MSpMat component_neighbor_vectors, NumericMatrix incoming_topics, NumericVector incoming_topic_sums, NumericMatrix incoming_document_sums, double alpha, double eta, int num_iterations);
RcppExport SEXP InteractiveTools_runGibbsCpp(SEXP incoming_component_assignmentsSEXP, SEXP component_doc_matrixSEXP, SEXP component_word_matrixSEXP, SEXP component_sizesSEXP, SEXP component_neighbor_vectorsSEXP, SEXP incoming_topicsSEXP, SEXP incoming_topic_sumsSEXP, SEXP incoming_document_sumsSEXP, SEXP alphaSEXP, SEXP etaSEXP, SEXP num_iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type incoming_component_assignments(incoming_component_assignmentsSEXP);
    Rcpp::traits::input_parameter< MSpMat >::type component_doc_matrix(component_doc_matrixSEXP);
    Rcpp::traits::input_parameter< MSpMat >::type component_word_matrix(component_word_matrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type component_sizes(component_sizesSEXP);
    Rcpp::traits::input_parameter< MSpMat >::type component_neighbor_vectors(component_neighbor_vectorsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type incoming_topics(incoming_topicsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type incoming_topic_sums(incoming_topic_sumsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type incoming_document_sums(incoming_document_sumsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type num_iterations(num_iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(runGibbsCpp(incoming_component_assignments, component_doc_matrix, component_word_matrix, component_sizes, component_neighbor_vectors, incoming_topics, incoming_topic_sums, incoming_document_sums, alpha, eta, num_iterations));
    return rcpp_result_gen;
END_RCPP
}
// initializeCpp
IntegerVector initializeCpp(MSpMat component_neighbor_vectors, NumericMatrix available_topic_matrix);
RcppExport SEXP InteractiveTools_initializeCpp(SEXP component_neighbor_vectorsSEXP, SEXP available_topic_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MSpMat >::type component_neighbor_vectors(component_neighbor_vectorsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type available_topic_matrix(available_topic_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(initializeCpp(component_neighbor_vectors, available_topic_matrix));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood
double loglikelihood(NumericMatrix topics, NumericMatrix document_sums, NumericMatrix topic_sums, double eta, double alpha);
RcppExport SEXP InteractiveTools_loglikelihood(SEXP topicsSEXP, SEXP document_sumsSEXP, SEXP topic_sumsSEXP, SEXP etaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type topics(topicsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type document_sums(document_sumsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type topic_sums(topic_sumsSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood(topics, document_sums, topic_sums, eta, alpha));
    return rcpp_result_gen;
END_RCPP
}
