# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runGibbsCpp <- function(incoming_component_assignments, component_doc_matrix, component_word_matrix, component_sizes, component_neighbor_vectors, incoming_topics, incoming_topic_sums, incoming_document_sums, alpha, eta, num_iterations) {
    .Call('InteractiveTools_runGibbsCpp', PACKAGE = 'InteractiveTools', incoming_component_assignments, component_doc_matrix, component_word_matrix, component_sizes, component_neighbor_vectors, incoming_topics, incoming_topic_sums, incoming_document_sums, alpha, eta, num_iterations)
}

initializeCpp <- function(component_neighbor_vectors, available_topic_matrix) {
    .Call('InteractiveTools_initializeCpp', PACKAGE = 'InteractiveTools', component_neighbor_vectors, available_topic_matrix)
}

loglikelihood <- function(topics, document_sums, topic_sums, eta, alpha) {
    .Call('InteractiveTools_loglikelihood', PACKAGE = 'InteractiveTools', topics, document_sums, topic_sums, eta, alpha)
}

